apiVersion: apps/v1
kind: Deployment
metadata:
  name: datalake-reader-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datalake-reader-server
  template:
    metadata:
      labels:
        app: datalake-reader-server
    spec:
      containers:
      - name: datalake-reader-server
        image: <>.azurecr.io/datalake-reader-server:v1
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: datalake-reader-server
spec:
  type: LoadBalancer
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: datalake-reader-server